@echo off
echo 🎨 Starting FBIV VPN Frontend Server...
cd /d "C:\Users\HP\Desktop\fbiv vpn mern\frontend"
echo 📁 Current directory: %CD%
echo ⚛️ Starting React development server...
echo 💡 Note: This may take a moment to start...
npx webpack serve --mode development --open
pause