const mongoose = require('mongoose');

// Connect to MongoDB
mongoose.connect('mongodb://localhost:27017/fbiv-vpn', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Server Schema
const serverSchema = new mongoose.Schema({
  location: String,
  country: String,
  city: String,
  flag: String,
  region: String,
  ping: Number,
  load: Number,
  bandwidth: String,
  maxSpeed: Number,
  uptime: Number,
  provider: String,
  datacenter: String,
  timezone: String,
  ipv6: Boolean,
  p2p: Boolean,
  cities: Number,
  users: Number,
  coordinates: {
    lat: Number,
    lng: Number
  },
  isActive: { type: Boolean, default: true }
});

const Server = mongoose.model('Server', serverSchema);

// Sample server data from the original HTML
const sampleServers = [
  {
    location: 'New York, USA',
    country: 'United States',
    city: 'New York',
    flag: '🇺🇸',
    region: 'Americas',
    ping: 18,
    load: 35,
    bandwidth: '1 Gbps',
    maxSpeed: 950,
    uptime: 99.9,
    timezone: 'EST (UTC-5)',
    provider: 'AWS',
    datacenter: 'US-East-1',
    ipv6: true,
    p2p: true,
    cities: 12,
    users: 1250,
    coordinates: { lat: 40.7128, lng: -74.0060 }
  },
  {
    location: 'Frankfurt, Germany',
    country: 'Germany',
    city: 'Frankfurt',
    flag: '🇩🇪',
    region: 'Europe',
    ping: 42,
    load: 58,
    bandwidth: '1 Gbps',
    maxSpeed: 920,
    uptime: 99.8,
    timezone: 'CET (UTC+1)',
    provider: 'Digital Ocean',
    datacenter: 'EU-Central-1',
    ipv6: true,
    p2p: true,
    cities: 8,
    users: 890,
    coordinates: { lat: 50.1109, lng: 8.6821 }
  },
  {
    location: 'Tokyo, Japan',
    country: 'Japan',
    city: 'Tokyo',
    flag: '🇯🇵',
    region: 'Asia',
    ping: 68,
    load: 23,
    bandwidth: '500 Mbps',
    maxSpeed: 480,
    uptime: 99.7,
    timezone: 'JST (UTC+9)',
    provider: 'Google Cloud',
    datacenter: 'Asia-Northeast-1',
    ipv6: true,
    p2p: false,
    cities: 6,
    users: 765,
    coordinates: { lat: 35.6762, lng: 139.6503 }
  },
  {
    location: 'London, UK',
    country: 'United Kingdom',
    city: 'London',
    flag: '🇬🇧',
    region: 'Europe',
    ping: 28,
    load: 41,
    bandwidth: '1 Gbps',
    maxSpeed: 980,
    uptime: 99.9,
    timezone: 'GMT (UTC+0)',
    provider: 'AWS',
    datacenter: 'EU-West-2',
    ipv6: true,
    p2p: true,
    cities: 15,
    users: 1180,
    coordinates: { lat: 51.5074, lng: -0.1278 }
  },
  {
    location: 'Sydney, Australia',
    country: 'Australia',
    city: 'Sydney',
    flag: '🇦🇺',
    region: 'Asia',
    ping: 95,
    load: 29,
    bandwidth: '500 Mbps',
    maxSpeed: 470,
    uptime: 99.6,
    timezone: 'AEDT (UTC+11)',
    provider: 'AWS',
    datacenter: 'AP-Southeast-2',
    ipv6: true,
    p2p: true,
    cities: 4,
    users: 623,
    coordinates: { lat: -33.8688, lng: 151.2093 }
  },
  {
    location: 'Toronto, Canada',
    country: 'Canada',
    city: 'Toronto',
    flag: '🇨🇦',
    region: 'Americas',
    ping: 22,
    load: 52,
    bandwidth: '1 Gbps',
    maxSpeed: 900,
    uptime: 99.8,
    timezone: 'EST (UTC-5)',
    provider: 'Digital Ocean',
    datacenter: 'Canada-Central',
    ipv6: true,
    p2p: true,
    cities: 7,
    users: 987,
    coordinates: { lat: 43.6532, lng: -79.3832 }
  },
  {
    location: 'Amsterdam, Netherlands',
    country: 'Netherlands',
    city: 'Amsterdam',
    flag: '🇳🇱',
    region: 'Europe',
    ping: 38,
    load: 33,
    bandwidth: '1 Gbps',
    maxSpeed: 940,
    uptime: 99.9,
    timezone: 'CET (UTC+1)',
    provider: 'Google Cloud',
    datacenter: 'EU-West-4',
    ipv6: true,
    p2p: true,
    cities: 5,
    users: 1056,
    coordinates: { lat: 52.3676, lng: 4.9041 }
  },
  {
    location: 'Singapore',
    country: 'Singapore',
    city: 'Singapore',
    flag: '🇸🇬',
    region: 'Asia',
    ping: 45,
    load: 28,
    bandwidth: '1 Gbps',
    maxSpeed: 950,
    uptime: 99.8,
    timezone: 'SGT (UTC+8)',
    provider: 'AWS',
    datacenter: 'AP-Southeast-1',
    ipv6: true,
    p2p: true,
    cities: 3,
    users: 1342,
    coordinates: { lat: 1.3521, lng: 103.8198 }
  },
  {
    location: 'Paris, France',
    country: 'France',
    city: 'Paris',
    flag: '🇫🇷',
    region: 'Europe',
    ping: 31,
    load: 45,
    bandwidth: '1 Gbps',
    maxSpeed: 920,
    uptime: 99.9,
    timezone: 'CET (UTC+1)',
    provider: 'AWS',
    datacenter: 'EU-West-3',
    ipv6: true,
    p2p: true,
    cities: 12,
    users: 1567,
    coordinates: { lat: 48.8566, lng: 2.3522 }
  },
  {
    location: 'Los Angeles, USA',
    country: 'United States',
    city: 'Los Angeles',
    flag: '🇺🇸',
    region: 'Americas',
    ping: 25,
    load: 39,
    bandwidth: '1 Gbps',
    maxSpeed: 960,
    uptime: 99.7,
    timezone: 'PST (UTC-8)',
    provider: 'Digital Ocean',
    datacenter: 'US-West-1',
    ipv6: true,
    p2p: true,
    cities: 8,
    users: 1789,
    coordinates: { lat: 34.0522, lng: -118.2437 }
  },
  {
    location: 'Stockholm, Sweden',
    country: 'Sweden',
    city: 'Stockholm',
    flag: '🇸🇪',
    region: 'Europe',
    ping: 29,
    load: 21,
    bandwidth: '1 Gbps',
    maxSpeed: 980,
    uptime: 99.9,
    timezone: 'CET (UTC+1)',
    provider: 'AWS',
    datacenter: 'EU-North-1',
    ipv6: true,
    p2p: true,
    cities: 2,
    users: 634,
    coordinates: { lat: 59.3293, lng: 18.0686 }
  },
  {
    location: 'São Paulo, Brazil',
    country: 'Brazil',
    city: 'São Paulo',
    flag: '🇧🇷',
    region: 'Americas',
    ping: 110,
    load: 67,
    bandwidth: '500 Mbps',
    maxSpeed: 450,
    uptime: 99.5,
    timezone: 'BRT (UTC-3)',
    provider: 'Azure',
    datacenter: 'Brazil-South',
    ipv6: false,
    p2p: true,
    cities: 3,
    users: 432,
    coordinates: { lat: -23.5558, lng: -46.6396 }
  },
  {
    location: 'Hong Kong',
    country: 'Hong Kong',
    city: 'Hong Kong',
    flag: '🇭🇰',
    region: 'Asia',
    ping: 61,
    load: 47,
    bandwidth: '1 Gbps',
    maxSpeed: 910,
    uptime: 99.7,
    timezone: 'HKT (UTC+8)',
    provider: 'Google Cloud',
    datacenter: 'Asia-East-2',
    ipv6: true,
    p2p: false,
    cities: 5,
    users: 1456,
    coordinates: { lat: 22.3193, lng: 114.1694 }
  },
  {
    location: 'Mumbai, India',
    country: 'India',
    city: 'Mumbai',
    flag: '🇮🇳',
    region: 'Asia',
    ping: 52,
    load: 61,
    bandwidth: '500 Mbps',
    maxSpeed: 480,
    uptime: 99.6,
    timezone: 'IST (UTC+5:30)',
    provider: 'Google Cloud',
    datacenter: 'Asia-South-1',
    ipv6: true,
    p2p: false,
    cities: 9,
    users: 2134,
    coordinates: { lat: 19.0760, lng: 72.8777 }
  },
  {
    location: 'Zurich, Switzerland',
    country: 'Switzerland',
    city: 'Zurich',
    flag: '🇨🇭',
    region: 'Europe',
    ping: 34,
    load: 26,
    bandwidth: '1 Gbps',
    maxSpeed: 970,
    uptime: 99.9,
    timezone: 'CET (UTC+1)',
    provider: 'AWS',
    datacenter: 'EU-Central-2',
    ipv6: true,
    p2p: true,
    cities: 2,
    users: 567,
    coordinates: { lat: 47.3769, lng: 8.5417 }
  }
];

async function seedDatabase() {
  try {
    // Clear existing servers
    await Server.deleteMany({});
    console.log('🗑️  Cleared existing servers');

    // Insert new servers
    await Server.insertMany(sampleServers);
    console.log(`✅ Inserted ${sampleServers.length} servers`);

    console.log('🎉 Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seedDatabase();